name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main  # pipeline jalan setiap kali push ke branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t php-ci-cd-app:latest .

      # 4️⃣ Tag image dengan nama Docker Hub kamu
      - name: Tag Docker image
        run: |
          docker tag php-ci-cd-app:latest ${{ secrets.DOCKER_USERNAME }}/php-ci-cd-app:latest

      # 5️⃣ Push ke Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/php-ci-cd-app:latest
